### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Spencer-0003** [ad-on-is/resticity#10]
Using the latest docker image also seems to happen completely randomly regardless if a backup is running or not.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x816836]

goroutine 18 [running]:
github.com/ad-on-is/resticity/internal.runHub()
        /build/internal/server.go:59 +0x116
created by github.com/ad-on-is/resticity/internal.RunServer in goroutine 1
        /build/internal/server.go:208 +0x1b0
```

**Comment by xXSkyWalkerXx1** [comment]
For me too, but it only seems to happen when crontab is in play. When I initiate the backup manually, I haven't had any problems so far.
